language: python

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt

jobs:
  include:
    - stage: test
      script:
        - python -m unittest discover -s tests
    - stage: deploy
      script:
        - pip install yolk3k
        - pip install twine
        - cd ci
        - pip install keyring==21.4.0
        - python upload_package.py

stages:
  - test
  - name: deploy
    if: branch = master