language: python
install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt
script: pytest
after_success:
- git config --global user.email "bumpversion-after-ci@example.com"
- git config --global user.name "Bumpversion after CI"
- bumpversion --verbose minor
- chmod 600 travis_deploy_key
- eval `ssh-agent -s`
- ssh-add travis_deploy_key
- git config --global push.default simple
- git remote add deploy $(git remote -v | sed -nre 's#^origin.*https://([^/]*)/([^
  ]*) *.*push.*#git@\1:\2#p')
- git push deploy HEAD:master
- python setup.py sdist
- pip install twine
- twine upload --config-file .pypirc-bot dist/*
before_install:
- openssl aes-256-cbc -K $encrypted_4f3b16254c24_key -iv $encrypted_4f3b16254c24_iv
  -in secret-files.tar.enc -out secret-files.tar -d
- tar xvf secret-files.tar
